version: '3'

services:
  carousel:
    image: erichen886/team-seeel:carousel
    build: .
    depends_on:
      - 'database'
    ports:
      - '3002:3002'
    command: 'npm start & npm run db:setup'
  database:
    image: mongo:latest

